import Link from 'next/link';
import { ShoppingBag, Utensils, Wrench, Store, Heart, ArrowRight } from 'lucide-react';
import { loadCatalog } from '@/lib/catalog';
import CatalogCard from '@/components/commerce/CatalogCard';
import styles from '@/components/commerce/marketplace.module.css';
export const dynamic='force-dynamic';
export default async function Home(){
 const {entries,businesses}=await loadCatalog();
 return <main className={styles.marketPage}><section className={styles.hero}><div className={styles.heroPrimary}><small>MARKETPLACE WARGA BANJARSARI</small><h1>Belanja kebutuhan.<br/>Dukung tetangga.</h1><p>Produk lokal, makanan rumahan, dan jasa pilihan warga.</p><Link href="/katalog">Jelajahi katalog →</Link></div><div className={styles.heroSecondary}><Utensils size={30}/><h2>Mau makan apa<br/>hari ini?</h2><p>Temukan menu dari dapur usaha sekitar Anda.</p><Link href="/makanan">Lihat pilihan makanan →</Link></div></section><nav className={styles.categoryBar} aria-label="Kategori belanja">{[{href:'/katalog?type=product',label:'Produk lokal',icon:ShoppingBag},{href:'/makanan',label:'Makanan',icon:Utensils},{href:'/jasa',label:'Jasa',icon:Wrench},{href:'/bisnis',label:'Toko warga',icon:Store},{href:'/favorites',label:'Favorit saya',icon:Heart}].map(({href,label,icon:Icon})=><Link key={href} href={href}><Icon size={26}/><span>{label}</span></Link>)}</nav><section><div className={styles.sectionTitle}><h2>Temukan kebutuhan Anda</h2><Link href="/katalog">Lihat semua →</Link></div><div className={styles.productGrid}>{entries.filter(i=>i.kind!=='service').map(item=><CatalogCard key={item.id} item={item}/>)}</div></section><section><div className={styles.sectionTitle}><h2>Jasa di sekitar Anda</h2><Link href="/jasa">Lihat semua →</Link></div><div className={styles.productGrid}>{entries.filter(i=>i.kind==='service').slice(0,5).map(item=><CatalogCard key={item.id} item={item}/>)}</div></section><section className={styles.shopStrip}><div><h2>Kenali usaha di Banjarsari</h2><p>{businesses.length} usaha dalam katalog. Temukan produk dan layanan dari warga sekitar.</p></div><Link className={styles.mainButton} href="/bisnis">Kunjungi toko warga <ArrowRight size={16}/></Link></section></main>;
}