'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, Eye, EyeOff, Leaf } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import styles from './marketplace.module.css';
export default function LocalAccount({profile=false,register=false}:{profile?:boolean;register?:boolean}) {
 const router=useRouter();
 const {user,role,loading,logout}=useAuth(); const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const [pending,setPending]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setPending(true);setError('');try{const r=await fetch('/api/local/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Login gagal');const next=new URLSearchParams(window.location.search).get('next');window.location.assign(d.user.role==='admin'?'/admin':next&&next.startsWith('/')&&!next.startsWith('//')&&!next.includes('\\')?next:'/');}catch(e){setError(e instanceof Error?e.message:'Koneksi gagal. Coba lagi.');}finally{setPending(false);}}
 return <main className={styles.authPage}><section className={styles.authIntro}><Leaf size={48}/><h1>Kebutuhan harian,<br/>dekat dari rumah.</h1><p>Belanja produk warga, pesan makanan, dan temukan jasa di Banjarsari dalam satu tempat.</p><span>PALUGADA · DARI WARGA UNTUK WARGA</span></section><section className={styles.authArea}><div className={styles.authCard}><Link href="/" className={styles.authLogo}>PALUGADA</Link>{profile&&loading?<p role="status">Memuat akun…</p>:profile&&user?<><h1>Halo, {user.displayName}</h1><p>{user.email}<br/>Peran: {role==='admin'?'Admin':'Customer'}</p><Link className={styles.mainButton} style={{marginTop:24}} href={role==='admin'?'/admin':'/orders'}>{role==='admin'?'Dashboard admin':'Pesanan saya'}<ArrowRight size={18}/></Link><button className={styles.authBack} onClick={async()=>{try{await logout();router.replace('/login');}catch{setError('Gagal keluar. Coba lagi.');}}}>Keluar dari akun</button></>:<><h1>{register?'Coba akun demo':'Masuk ke akun'}</h1><p>{register?'Pendaftaran belum tersedia. Gunakan akun demo yang disiapkan.':'Lanjutkan belanja dan pantau pesanan Anda.'}</p><form onSubmit={submit}><label>Username atau email<input autoComplete="username" autoCapitalize="none" spellCheck={false} required value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin atau user"/></label><label>Kata sandi<div className={styles.passwordField}><input type={show?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Masukkan kata sandi"/><button type="button" aria-label={show?'Sembunyikan kata sandi':'Tampilkan kata sandi'} onClick={()=>setShow(!show)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label><button className={styles.mainButton} disabled={pending}>{pending?'Memeriksa…':'Masuk'}<ArrowRight size={18}/></button></form><p className={styles.authHint}>Mode demo lokal. Pesanan uji tersimpan di perangkat server; tidak ada pembayaran nyata.</p></>}{error&&<p role="alert" className={styles.authError}>{error}</p>}<Link href="/" className={styles.authBack}>← Kembali berbelanja</Link></div></section></main>;
}