'use client';
import { useEffect, useRef, useState } from 'react';
import { Download, Upload, TrendingUp, PackageCheck, CalendarDays, Info, RefreshCw } from 'lucide-react';
import type { ForecastResult, StockInput } from '@/lib/monitoring/forecast';
import { forecastCsv } from '@/lib/monitoring/forecast-csv';
import styles from './analysis.module.css';
import dashboard from './monitoring.module.css';
interface ForecastData { source: 'sample' | 'upload'; asOf: string; products: StockInput[]; results: ForecastResult[] }
const download = (name: string, text: string) => { const url = URL.createObjectURL(new Blob(['\uFEFF' + text], { type: 'text/csv;charset=utf-8;' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
const ForecastDashboard = () => {
  const [data, setData] = useState<ForecastData | null>(null);
  const [loading, setLoading] = useState(true), [error, setError] = useState('');
  const [asOf, setAsOf] = useState('2026-09-28'), [selected, setSelected] = useState(''), [kind, setKind] = useState('all');
  const input = useRef<HTMLInputElement>(null);
  const loadSample = async () => {
    setLoading(true); setError('');
    try { const response = await fetch('/api/local/forecast'); const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body.data); setAsOf(body.data.asOf); setSelected(body.data.results[0]?.id ?? ''); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Gagal memuat data.'); } finally { setLoading(false); }
  };
  useEffect(() => { const timer = setTimeout(() => void loadSample(), 0); return () => clearTimeout(timer); }, []);
  const importFile = async (file?: File) => {
    if (!file) return; setError(''); if (file.size > 1_000_000) { setError('Ukuran CSV maksimal 1 MB.'); return; } setLoading(true);
    try { const csv = await file.text(); const response = await fetch('/api/local/forecast', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ csv, asOf }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body.data); setSelected(body.data.results[0]?.id ?? ''); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Impor gagal.'); } finally { setLoading(false); if (input.current) input.current.value = ''; }
  };
  const rows = data?.results.filter((r) => kind === 'all' || r.kind === kind) ?? [];
  const current = data?.results.find((r) => r.id === selected), product = data?.products.find((r) => r.id === selected);
  const riskLabels = { low: 'Perlu disiapkan', excess: 'Stok berlebih', healthy: 'Stok cukup', insufficient: 'Data belum cukup' };
  const chart = product && current?.eligible ? [...[...product.history].sort((a,b)=>a.date.localeCompare(b.date)).slice(-14).map((d) => ({ ...d, future: false })), ...current.predictions.slice(0, 7).map((d) => ({ ...d, future: true }))] : [];
  const max = Math.max(1, ...chart.map((d) => d.quantity));
  return <main className={dashboard.content}><div className={dashboard.heading}><div><span className={dashboard.eyebrow}>ANALISIS PERMINTAAN & INVENTORI</span><h1>Siapkan stok dengan lebih terukur.</h1><p>Perkiraan barang dan rencana produksi makanan dari histori penjualan harian.</p></div><button className={dashboard.iconButton} onClick={loadSample} disabled={loading}><RefreshCw size={16} /> Muat contoh</button></div>
    <div className={dashboard.sourceNote}><Info size={16} /><strong>{data?.source === 'upload' ? 'Data CSV yang Anda impor' : 'Dataset simulasi · 56 hari'}</strong><span>{data?.source === 'upload' ? 'Dianalisis untuk sesi ini; tidak disimpan ke database.' : 'Dataset latihan terpisah dari pesanan demo. Bukan prediksi penjualan nyata.'}</span></div>
    <section className={styles.importPanel}><h2>Gunakan data penjualan Anda</h2><p>Isi satu baris per produk per hari, termasuk 0 saat tidak ada penjualan. Stok layak jual harus sama di seluruh baris produk.</p><div className={styles.importActions}><label>Tanggal akhir data<input type="date" value={asOf} onChange={(e) => setAsOf(e.target.value)} /></label><button onClick={() => data && download('palugada-template-forecast.csv', forecastCsv(data.products))} disabled={!data || loading}><Download size={16} /> Unduh contoh CSV</button><button onClick={() => input.current?.click()} disabled={loading}><Upload size={16} /> Impor CSV</button><input ref={input} type="file" accept=".csv,text/csv" onChange={(e) => void importFile(e.target.files?.[0])} hidden /></div></section>
    {error && <div className={styles.error} role="alert">{error}</div>}{loading ? <p className={dashboard.state} role="status">Menganalisis histori penjualan…</p> : data && <>
      <div className={styles.forecastMetrics}><article><CalendarDays size={22} /><span>Tanggal perkiraan pertama</span><strong>{current?.predictions[0]?.date ?? '—'}</strong><small>Setelah tanggal akhir data</small></article><article><TrendingUp size={22} /><span>Produk dapat dianalisis</span><strong>{data.results.filter((r) => r.eligible).length} / {data.results.length}</strong><small>Minimal 28 hari lengkap</small></article><article><PackageCheck size={22} /><span>Perlu persiapan stok</span><strong>{data.results.filter((r) => r.eligible && r.suggested > 0).length} produk</strong><small>Keputusan akhir tetap pada seller</small></article></div>
      <section className={dashboard.panel}><div className={dashboard.panelHeading}><div><h2>Rekomendasi per produk</h2><p>Saran tambah mengikuti periode rencana dan umur simpan tiap produk.</p></div><select aria-label="Jenis produk forecasting" value={kind} onChange={(e) => setKind(e.target.value)}><option value="all">Semua produk</option><option value="RETAIL">Barang</option><option value="FOOD">Makanan</option></select></div><div className={dashboard.tableWrap} tabIndex={0}><table><thead><tr><th>Produk</th><th>Besok</th><th>7 hari</th><th>Stok layak jual</th><th>Saran tambah</th><th>Kondisi</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td><button className={dashboard.orderLink} onClick={() => setSelected(r.id)}>{r.name}</button><small>{r.kind === 'FOOD' ? 'Makanan' : 'Barang'} · {r.unit}</small></td><td>{r.eligible ? r.tomorrow : '—'}</td><td>{r.eligible ? r.week : '—'}</td><td>{r.onHand}<small>+{r.incoming} masuk tepat waktu</small></td><td><strong>{r.eligible ? r.suggested : '—'}</strong><small>{r.eligible ? `Untuk ${r.planningDays} hari` : 'Belum direkomendasikan'}</small></td><td><span className={styles.risk} data-risk={r.risk}>{riskLabels[r.risk]}</span></td></tr>)}</tbody></table></div>{!rows.length && <p className={dashboard.empty}>Tidak ada produk untuk jenis ini.</p>}</section>
      {current && <section className={dashboard.panel}><div className={dashboard.panelHeading}><div><h2>{current.name}</h2><p>{current.eligible ? `${current.method} · ${current.historyDays} hari tercatat · acuan ${data.asOf}` : current.reason}</p></div>{current.trendPercent !== null && <span className={styles.trend}>{current.trendPercent > 0 ? '+' : ''}{current.trendPercent}% permintaan 7 hari</span>}</div>{current.eligible && <><div className={styles.chartLegend}><span>■ Penjualan tercatat (14 hari)</span><span>▧ Perkiraan (7 hari)</span></div><div className={styles.forecastChart} role="img" aria-label={`Perkiraan besok ${current.tomorrow} ${current.unit}.`}>{chart.map((d) => <div key={d.date} title={`${d.date}: ${d.quantity} ${current.unit}${d.future ? ' (perkiraan)' : ''}`}><div><span data-future={d.future} style={{ height: `${d.quantity / max * 100}%` }} /></div><small>{d.date.slice(-2)}</small></div>)}</div>
        <div className={styles.explanation}><div><h3>Rekomendasi tindakan</h3><p>{current.suggested > 0 ? `Siapkan tambahan ${current.suggested} ${current.unit} untuk ${current.planningDays} hari rencana.` : current.risk === 'excess' ? 'Tunda tambahan stok dan prioritaskan stok yang sudah ada.' : 'Stok dan barang masuk mencukupi rencana saat ini.'}</p><p>{current.reason}</p><p>Target {current.stockTarget} − stok {current.onHand} − masuk {current.incoming} = tambahan {current.suggested}. Barang masuk dihitung hanya jika tiba sebelum kebutuhan.</p></div><div><h3>Seberapa baik modelnya?</h3><p>Rata-rata meleset <strong>{current.mae?.toFixed(2)} {current.unit}/hari</strong> pada uji bergulir 14 hari terakhir. {current.wape === null ? 'WAPE tidak tersedia saat penjualan aktual nol.' : `WAPE ${current.wape.toFixed(1)}%.`}</p><p>Dipilih dari 4 metode dengan error validasi terendah. Ini bukan jaminan akurasi; promo, cuaca, stok habis, dan kedaluwarsa belum dimodelkan.</p></div></div>
        <details className={styles.methodDetails}><summary>Model pembanding & angka perkiraan</summary><div className={styles.methodGrid}>{current.validation.map((m) => <p key={m.method}>{m.method}: MAE <strong>{m.mae.toFixed(2)}</strong></p>)}{current.predictions.slice(0, 7).map((d) => <p key={d.date}>{d.date}: {d.quantity} {current.unit}</p>)}</div><p>Uji memakai data sebelum hari uji saja. Buffer barang = MAE × √hari rencana. Makanan tanpa buffer, dibatasi umur simpan. Bukan interval keyakinan statistik.</p></details></>}</section>}
    </>}
  </main>;
};
export default ForecastDashboard;
