'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { accountFetch } from '@/lib/account-client';
import type { OwnedBusiness, SellerListing } from '@/lib/accounts/types';
import type { MonitoringData } from '@/lib/monitoring/types';
import { rupiah, summarizeOrders } from '@/lib/monitoring/metrics';
import { LOCAL_PREVIEW } from '@/lib/local-preview';
import BusinessFields from './BusinessFields';
import styles from './accounts.module.css';
interface SellerData { business: OwnedBusiness; listings: SellerListing[]; data: MonitoringData }
const blankListing = (kind: SellerListing['kind']) => ({ name: '', description: '', price: 0, stock: 0, image: '', active: true, kind });
export default function SellerDashboard({ section = 'overview' }: { section?: string }) {
  const [data, setData] = useState<SellerData | null>(null), [error, setError] = useState(''), [loading, setLoading] = useState(true), [pending, setPending] = useState(false), [message, setMessage] = useState('');
  const [draft, setDraft] = useState<ReturnType<typeof blankListing> & { id?: string }>(() => blankListing(section === 'food' ? 'FOOD' : section === 'services' ? 'SERVICE' : 'RETAIL'));
  const [business, setBusiness] = useState<OwnedBusiness | null>(null);
  const [method, setMethod] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await accountFetch('/api/seller'), body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); setBusiness(body.business); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Data toko gagal dimuat.'); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  async function save(action: string) {
    setPending(true); setError(''); setMessage('');
    try { const response = await accountFetch('/api/seller', { method: 'POST', body: JSON.stringify({ ...(action === 'listing' ? draft : business), businessId: data?.business.id, action }) }), body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); setDraft(blankListing(draft.kind)); setMessage('Perubahan toko berhasil disimpan.'); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Perubahan gagal disimpan.'); } finally { setPending(false); }
  }
  const titles: Record<string,string> = { overview:'Ringkasan toko', products:'Produk', food:'Makanan / menu', services:'Jasa', orders:'Pesanan toko', bookings:'Booking toko', stock:'Stok & persiapan', payments:'Pembayaran toko', analytics:'Analytics toko', settings:'Pengaturan toko' };
  if (loading) return <main className={styles.page} role="status">Memuat toko Anda…</main>;
  if (!data) return <main className={styles.page}><h1>Akses toko belum tersedia</h1><p role="alert" className={styles.error}>{error}</p><button className={styles.secondary} onClick={load}>Coba lagi</button></main>;
  const metrics = summarizeOrders(data.data.orders), listingSection = ['products','food','services','stock'].includes(section);
  const listings = data.listings.filter(item => section === 'stock' ? item.kind !== 'SERVICE' : item.kind === (section === 'food' ? 'FOOD' : section === 'services' ? 'SERVICE' : 'RETAIL'));
  return <main className={styles.page}><span className={styles.status}>SELLER · TOKO SENDIRI</span><h1>{titles[section]}</h1><p>{data.business.businessName}</p><p className={styles.muted}>Business ID: {data.business.id}</p>{error && <p className={styles.error} role="alert">{error}</p>}{message && <p className={styles.notice} role="status">{message}</p>}
    {['overview','analytics'].includes(section) && <><div className={styles.stats}><article>GMV terbayar<strong>{rupiah(metrics.gmv)}</strong><small>Pesanan milik toko ini</small></article><article>Pesanan<strong>{data.data.orders.length}</strong><small>Semua status</small></article><article>Katalog aktif<strong>{data.listings.filter(item => item.active).length}</strong><small>Produk, makanan, dan jasa</small></article></div><section className={styles.card}><h2>Langkah berikutnya</h2><p>{data.listings.length ? 'Periksa stok, pantau transaksi, lalu gunakan histori penjualan toko untuk merencanakan persiapan.' : 'Toko sudah aktif. Tambahkan produk, menu makanan, atau layanan pertama Anda.'}</p><div className={styles.actions}><Link className={styles.primary} href="/seller/products">Kelola produk</Link><Link className={styles.secondary} href="/seller/forecast">Rencana stok besok</Link><Link className={styles.secondary} href="/seller/financial-projection">Proyeksi keuangan</Link></div></section></>}
    {listingSection && <><p className={styles.notice}>{LOCAL_PREVIEW ? 'Katalog seller pada demo tersimpan lokal. Publikasi ke katalog transaksi demo belum dihubungkan; pesanan customer existing tetap memakai katalog uji.' : 'Produk disimpan ke katalog usaha melalui server. Stok di sini adalah catatan persiapan; integrasi reservasi transaksi production belum tersedia.'}</p><div className={styles.list}>{listings.length ? listings.map(item => <article className={styles.card} key={item.id}><h2>{item.name}</h2><p>{rupiah(item.price)} · {item.active ? 'Aktif' : 'Nonaktif'}</p><p>Stok persiapan: <strong>{item.stock}</strong></p><p className={styles.muted}>ID untuk CSV forecast: {item.id}</p><button className={styles.secondary} onClick={() => setDraft(item)}>Edit {item.name}</button></article>) : <p className={styles.notice}>Belum ada item pada kategori ini.</p>}</div><form className={`${styles.card} ${styles.form}`} onSubmit={event => { event.preventDefault(); void save('listing'); }}><h2>{draft.id ? 'Edit item toko' : 'Tambah item toko'}</h2><label>Nama produk / jasa<input required minLength={2} maxLength={120} value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })}/></label><label>Deskripsi<textarea maxLength={2000} value={draft.description} onChange={event => setDraft({ ...draft, description: event.target.value })}/></label><div className={styles.fields}><label>Harga (Rp)<input type="number" min={0} max={1000000000} required value={draft.price} onChange={event => setDraft({ ...draft, price: Number(event.target.value) })}/></label><label>Stok persiapan<input type="number" min={0} max={1000000} required value={draft.stock} onChange={event => setDraft({ ...draft, stock: Number(event.target.value) })}/></label></div><label>URL foto HTTPS<input type="url" maxLength={2000} value={draft.image} onChange={event => setDraft({ ...draft, image: event.target.value })}/></label><label className={styles.check}><input type="checkbox" checked={draft.active} onChange={event => setDraft({ ...draft, active: event.target.checked })}/>Aktifkan item</label><div className={styles.actions}><button className={styles.primary} disabled={pending}>{pending ? 'Menyimpan…' : 'Simpan item'}</button>{draft.id && <button type="button" className={styles.secondary} onClick={() => setDraft(blankListing(draft.kind))}>Batal edit</button>}</div></form></>}
    {['orders','payments','bookings'].includes(section) && <section className={styles.card}><h2>Transaksi milik toko</h2><p className={styles.muted}>Hanya transaksi dengan businessId toko ini yang ditampilkan. Transaksi lama tanpa ID kepemilikan tidak diambil berdasarkan nama.</p>{section === 'payments' && <label>Metode pembayaran<select className={styles.filter} value={method} onChange={event => setMethod(event.target.value)}><option value="">Semua metode</option>{['COD','Transfer bank','QRIS'].map(value => <option key={value}>{value}</option>)}</select></label>}{section === 'bookings' ? data.data.bookings.length ? data.data.bookings.map(item => <article key={item.id} className={styles.card}><h2>{item.service}</h2><p>{item.customer} · {item.schedule} · {item.status}</p></article>) : <p className={styles.notice}>Belum ada booking milik toko.</p> : data.data.orders.filter(order => !method || order.method === method).length ? <div className={styles.tableWrap} tabIndex={0}><table><thead><tr>{['Order ID','Customer','Total','Metode','Status','Payment'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{data.data.orders.filter(order => !method || order.method === method).map(order => <tr key={order.id}><td>{order.id}</td><td>{order.customer}</td><td>{rupiah(order.total)}</td><td>{order.method}</td><td>{order.status}</td><td>{order.payment}</td></tr>)}</tbody></table></div> : <p className={styles.notice}>Belum ada transaksi milik toko pada filter ini. Integrasi lifecycle operasional tetap mengikuti domain transaksi existing.</p>}</section>}
    {section === 'settings' && business && <form className={`${styles.card} ${styles.form}`} onSubmit={event => { event.preventDefault(); void save('settings'); }}><h2>Profil toko</h2><BusinessFields value={business} onChange={value => setBusiness({ ...business, ...value })} onError={setError} disabled={pending}/><button className={styles.primary} disabled={pending}>Simpan pengaturan toko</button><p className={styles.muted}>Pemilik dan status approval tidak dapat diubah dari form ini.</p></form>}
  </main>;
}
